CHANGES.rst, apacheconfig/__init__.py, apacheconfig/lexer.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
To address issue https://github.com/etingof/apacheconfig/issues/8
=> Allow empty value syntax in the option-value pair

CHANGES.rst, README.md, apacheconfig/apacheconfigtool.py, apacheconfig/loader.py, tests/integration/test_perl_samples.py, tests/unit/test_loader.py
The `no escape` option can be used to [preserve the leftovers of special escape chars](https://metacpan.org/source/TLINDEN/Config-General-2.63/General.pm#L1216) in the values. This hopefully addresses issue #6 .
=> Add noescape option

README.md, apacheconfig/apacheconfigtool.py, apacheconfig/parser.py, tests/unit/test_parser.py
Hey ! Today it's a PR coming from us :tada:
I banged my head another time before realizing the parser actually didn't stripped useless trailing white-spaces for values.
Maybe a side-effect of a previous commit ?
It looks like this feature was not tested either.
Anyway, here we are, I let you take a look to the changes and keep me posted :ok_hand:
Bye :wave: 
(Ofc feel free to edit my branch directly if you want)
PS : The `\` added are for Python linters, we could remove them if you want too.
=> Right-strips trailing spaces by default and adds an option to disable it

apacheconfig/parser.py
The ply parser calls `p_error` with `None` if the syntax error is due to reaching the `end-of-file`.
=> return clearer error message

apacheconfig/loader.py
Hello,
here is trivial fix which handle config format like this
```
Include "conf/marketing_data_list.conf"
Include "conf/ip_database.conf"
```
P.S. I not completely understand why you using your own `_unquote_tag` function instead `.strip("\"\'")`
=> Fixed quoting issue for includes

apacheconfig/loader.py, apacheconfig/parser.py, tests/unit/test_loader.py, tests/unit/test_parser.py
To make the whitespace-preserving PR a bit easier to parse, we need to refactor and simplify the BNF a bit. Here's the parts that are not related to the whitespace PR. In particular, we remove the `statements` object and consolidated some of the the routines in `loader.py`.
Most of this is moving code around-- the new bits primarily involve combining parts of the merging logic from across `merge_contents`, `merge_statements`, and `merge_dicts` into `merge_item`.
I'm not quite familiar with the `Config::General` flags, but the purpose of `merge_lists` and much of the existing `merge_dicts` implementation wasn't entirely clear to me, so even though the existing tests continued to pass, there may be some use case I'm missing here.
Fixes #44.
=> Combine merging logic to simplify BNF

.travis.yml, apacheconfig/__init__.py, apacheconfig/apacheconfigtool.py, apacheconfig/lexer.py, apacheconfig/loader.py, apacheconfig/parser.py
Using flake8! :) Almost all the edits are just wrapping lines to under 80 characters, as well as defining module exports explicitly in `__init__.py` using `__all__`.
Fixes #46.
=> Lint cleanup and add flake8 to travis

apacheconfig/lexer.py, apacheconfig/parser.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
Should leave all functionality the same. PR maintains all prior functionality (parser understands, but throws away whitespace information). Next PR will have the parser be able to retain whitespace information conditionally!
Now that we're consuming whitespace during lexing rather than parsing, the nostrip flag must be implemented at the lexing layer. Commit [`4f15118`](https://github.com/etingof/apacheconfig/commit/4f15118fb81a723e552a745043cd78d3c1e94855) is my first shot at this, but there may be a more canonical way to construct different lexing rules via PLY.
=> Start tokenizing and parsing whitespace

apacheconfig/lexer.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
Preserving the hash in the AST for hash comments makes processing down-the-line easier. May be helpful for C-style comments as well!
=> Include hash in hashcomment AST

apacheconfig/lexer.py, apacheconfig/parser.py, tests/unit/test_lexer.py
Missed includes in the original whitespace-preserving PR. Hopefully this makes sense! We're preserving all the whitespace data before the included filename, though the parser throws that information out for now.
=> lexer/parser: save but ignore whitespace and formatting data for includes

apacheconfig/lexer.py, apacheconfig/parser.py, tests/integration/test_perl_samples.py, tests/unit/test_lexer.py, tests/unit/test_loader.py
fixes #39
Now the lexer preserves escaped newlines. The parser throws them out for the time being.
=> fix: preserve escaped newlines and ignore them in parser

apacheconfig/parser.py, tests/unit/test_parser_whitespace.py
up until now, we've been ignoring all the whitespace information in parser.py-- let's create a flag so we can decide not to ignore it, and test that flag as much as we can.
~~Depends on #54 to pass some tests -- see `add whitespace parser tests` commit for this PR's diff.~~ EDIT: #54 merged!
=> Create a preserve-whitespace option for the parser

apacheconfig/lexer.py, apacheconfig/parser.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
Fixes #51 
Fixes #37 
Fixes #21 (I think this one's already been fixed-- just tagging it so all the comment/hash escape issues can get closed)
Also need this for my one-to-one writable loader to preserve hash escapes properly :)
Some context: since the lexer's `OPTION_AND_VALUE` regex disallowed `#` in `value`, values with escaped hashes ended up being processed in `multiline_OPTION_AND_VALUE`. By allowing the regex to consume escaped hashes, this doesn't happen, the value is processed properly and so are inline hash comments.
=> fix(lexer): option_and_value can consume and preserve escaped hashes

CHANGES.rst, README.md, apacheconfig/apacheconfigtool.py, apacheconfig/parser.py, tests/unit/test_parser_whitespace.py
Also, renamed `preserve_whitespace` into totally unreadable
`preservewhitespace` for the sake of consistency.
=> Add missing `preservewhitespace` option to apacheconfigtool

apacheconfig/lexer.py, apacheconfig/parser.py, tests/unit/test_lexer.py, tests/unit/test_parser.py, tests/unit/test_parser_whitespace.py
fix #33 
One behavior change is that if C-style comments are disabled, lines like
```
/*comment*/
/*
*/
```
are interpreted as argument-less directives, like: `{"/*comment*/": None, "/*": None, "*/": None}`. This is consistent with the behavior of Perl's Config::General module.
=> fix(lexer): handle no-argument directives properly

README.md, apacheconfig/apacheconfigtool.py, apacheconfig/lexer.py, tests/unit/test_lexer.py
fixes #51 ! Adds a new option that enables escaped newlines at the end of hash comments to continue them.
=> Multi-line hash comments

apacheconfig/lexer.py, apacheconfig/loader.py, apacheconfig/parser.py, tests/unit/test_lexer.py, tests/unit/test_parser.py, tests/unit/test_parser_whitespace.py
We'd like to be able to write block arguments in the future (while keeping the tag the same)-- so here's a shot at tokenizing that in the lexer, rather than the loader.
Depends on #59 , and should be rebased/merged after that one is. See last 3 commits for full diff of this PR.
=> Tokenize block names

apacheconfig/lexer.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
fixes #61 
Depends on #60 -- should be merged/rebase afterwards. To see diff, check out the most recent commit.
Beforehands, since we were only matching `<.*>` lines for opening tags, something like:
```
<block \
name>
```
wouldn't get matched. This changes the open_tag lexing so if it matches on `<.*\`, it performs the regular multiline lexing routine properly!
=> Multi-line tag names supported properly

CHANGES.rst, README.md, apacheconfig/apacheconfigtool.py, apacheconfig/lexer.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
Fixes #64 -- disables self-closing tags. Falls back to tokenizing them as open tags, if possible.
This matches native Apache parser behavior.
=> Add option to disable empty-element tags

apacheconfig/lexer.py, tests/unit/test_lexer.py, tests/unit/test_parser.py
Escaping the hashes should fix #69 !
Depends on #70 just so test suites pass.
=> Escape hashes in regexes

apacheconfig/lexer.py, tests/unit/test_lexer.py
This was my bad-- the multiline hash comments were eating the rest of the file instead of ending properly at the next unescaped newline. Fixed the regex to cover all the cases and added lots more tests.
=> Fix multiline hash comments

apacheconfig/lexer.py, apacheconfig/parser.py, tests/unit/test_lexer.py, tests/unit/test_loader.py, tests/unit/test_parser.py
~~Reports of bug in #83, heredoc values throwing away whitespace. Added tests to catch
this.~~
Fixes #83 and adds more tests for it.
=> Heredocs should preserve whitespace with line breaks.

CHANGES.rst, apacheconfig/lexer.py, apacheconfig/loader.py, apacheconfig/parser.py, apacheconfig/reader.py, apacheconfig/wloader.py, tests/integration/samples/perl-config-general/combination-of-constructs.conf, tests/integration/test_perl_samples.py, tests/unit/test_lexer.py, tests/unit/test_loader.py, tests/unit/test_parser.py, tests/unit/test_wloader.py
Fixes #85.
This is a pass at the following tasks, needed for unicode support:
* Decode `utf-8` wherever we process input. The places where we expect input are relatively few -- all through the loader
* import unicode_literal from `__future__` on all files with string literals
* `str` conversions go through the Python 2/3-compatible `six.text_type`
This may not be a comprehensive list, and my first pass may not have knocked them all out thoroughly. Let's see how Travis handles this.
=> Initial pass at Unicode plumbing.

apacheconfig/__init__.py, apacheconfig/wloader.py, tests/unit/test_wloader.py
Fixes #49.
As we mentioned a while ago, I moved this decision out to a separate PR. Good news is that this will hopefully be the final one to reach a baseline of functionality and close #49 :)
Tried to match the interface for `make_loader`; Right now the `WritableLoader` object is pretty bare bones, but can be extended to do other things in the future, like the regular `Loader` object.
Also rolled in a couple of very small fixes; let me know if you prefer these in a separate PR.
Let me know what you think!
=> Exposed public interface for writable loader

apacheconfig/lexer.py, apacheconfig/parser.py, tests/__main__.py, tests/unit/test_loader.py, tests/unit/test_wloader.py
After doing some more testing, it turns out some Python3 tests were silently failing! Fixed `tests/__main__.py` to forward exit codes correctly.
Lastly, there is also a deprecation warning we're getting sometimes from `lex`, which I'll investigate in a separate issue: #96 
This might want to go out in a point release fix (0.3.1?) once we land it!
=> Forward error code in `tests/__main__.py` and fix tests

.travis.yml, apacheconfig/__init__.py, apacheconfig/apacheconfigtool.py, apacheconfig/lexer.py, apacheconfig/loader.py, apacheconfig/parser.py, apacheconfig/reader.py, apacheconfig/wloader.py, setup.cfg, tests/integration/test_perl_samples.py, tests/unit/test_lexer.py, tests/unit/test_loader.py, tests/unit/test_parser.py, tests/unit/test_parser_whitespace.py, tests/unit/test_wloader.py
Sorted imports using [isort](https://pypi.python.org/pypi/isort/) and added an isort check to the Travis lint run.
Let me know if you have thoughts on the configuration.
Fixes #91
=> Sort import orders.
